In [2]:
import json
import numpy as np
import scipy as scs
import pandas as pd
from pandas.io.json import json_normalize 

print("Starting...")

data = json.load(open('formatted_tweets.json'))
data = data["tweets"]
json_normalize(data)
df = pd.DataFrame(data)

print("starting...")

list_id = sorted(set(df["id"]))
df["id"] = df["id"].apply(lambda x: list_id.index(x))

print("done...")

list_id = sorted(set(df["user_id"]))
df["user_id"] = df["user_id"].apply(lambda x: list_id.index(x))

Starting...
starting...
done...

In [3]:
print("done...")


df.to_csv("cleaned_dataset", index=False)


print(df.head())

done...
                       created_at  favorite_count hash_tags      id  \
0  Tue Jun 30 13:02:48 +0000 2015               0        []  185364
1  Mon May 24 12:23:36 +0000 2010               0        []   19204
2  Fri Sep 18 14:07:27 +0000 2015               6        []  351952
3  Fri Sep 25 18:52:43 +0000 2015               0        []  362679
4  Wed Jun 10 17:06:59 +0000 2015               0        []  117575

  in_reply_to_status_id  possibly_sensitive  retweet_count  \
0                  NULL               False              0
1                  NULL               False              0
2                  NULL               False              3
3                  NULL               False              1
4                  NULL               False              0

                                          tweet_text  user_id user_mentions
0  Walmart bakes ISIS cake, rejects Confederate f...    43891            []
1  UK bans doctor who linked autism to vaccine: B...    13550            []
2  Doritos unveils rainbow chips to support LGBT ...    83451            []
3  Mike Huckabee Is Having A Meltdown About Those...    10030            []
4  The only good news about the McKinney pool par...    79346  [2347049341]

In [7]:
import csv
df.to_csv("cleaned_dataset_2", encoding='utf-8', index=False, quoting=csv.QUOTE_ALL)

In [8]:
df

,created_at,favorite_count,hash_tags,id,in_reply_to_status_id,possibly_sensitive,retweet_count,tweet_text,user_id,user_mentions
0,Tue Jun 30 13:02:48 +0000 2015,0,[],185364,NULL,False,0,"Walmart bakes ISIS cake, rejects Confederate f...",43891,[]
1,Mon May 24 12:23:36 +0000 2010,0,[],19204,NULL,False,0,UK bans doctor who linked autism to vaccine: B...,13550,[]
2,Fri Sep 18 14:07:27 +0000 2015,6,[],351952,NULL,False,3,Doritos unveils rainbow chips to support LGBT ...,83451,[]
3,Fri Sep 25 18:52:43 +0000 2015,0,[],362679,NULL,False,1,Mike Huckabee Is Having A Meltdown About Those...,10030,[]
4,Wed Jun 10 17:06:59 +0000 2015,0,[],117575,NULL,False,0,The only good news about the McKinney pool par...,79346,[2347049341]
5,Tue Sep 01 22:26:54 +0000 2015,0,[],323544,NULL,False,2,Reporter: how u feel about ya breakup with mis...,132628,[]
6,Thu Sep 10 18:18:01 +0000 2015,0,[],339011,NULL,False,0,Rupert Murdoch Buys National Geographic Magazi...,34808,[]
7,Sat Nov 21 08:52:05 +0000 2015,0,[],467443,NULL,False,0,Man forced to post passport on Facebook to pro...,80485,[]
8,Fri Dec 04 08:10:20 +0000 2015,0,[],503396,NULL,False,0,RIP Scott Weiland. https://t.co/9j0bY8Crwp,58067,[]
9,Tue Dec 01 22:01:45 +0000 2015,0,[],492131,NULL,False,0,Trump blames 'ancient' tech for lack of video ...,47081,[]
10,Fri Apr 30 20:07:25 +0000 2010,0,[],11240,NULL,False,0,rip gerry ryan,153422,[]
11,Fri Nov 20 21:38:26 +0000 2015,0,[],465215,NULL,False,0,"Phuc Dat Bich Wants Facebook To Know That Yes,...",146233,[]
12,Wed Jun 17 00:53:12 +0000 2015,0,[],148380,NULL,False,0,Ex-NAACP leader Rachel Dolezal: 'I identify as...,83979,[]
13,Thu Jun 18 16:11:29 +0000 2009,0,[],60655,NULL,False,0,George Tiller shooting prompts PETA ad campaig...,153065,[]
14,Wed Jul 22 12:52:38 +0000 2015,0,[],231057,NULL,False,0,Sandra Bland Death: Texas to Look Into Alleged...,176598,[14173315]
15,Tue Aug 11 20:28:14 +0000 2015,0,[hustle411],296526,NULL,False,0,"""Can it get any worse for Whole Foods?"" 👂👀 #hu...",68508,[]
16,Fri Jul 31 15:09:46 +0000 2009,0,[],78966,NULL,False,0,Najava: Nikon D300S http://tinyurl.com/krrpf3,164964,[]
17,Mon Nov 02 21:16:05 +0000 2015,14,[OpKKK],430411,NULL,False,23,https://t.co/td9s7Q2CVF\nThat's bcuz #OpKKK di...,163763,[]
18,Sun Oct 11 00:01:06 +0000 2015,0,[],393153,NULL,False,0,Richard Gere Went Homeless in NYC to See What ...,102900,[]
19,Thu Jun 11 20:44:07 +0000 2015,0,[],126394,NULL,False,0,"Dusty Rhodes, 'The American Dream,' dies at ag...",171011,[]
20,Fri Nov 20 01:48:58 +0000 2015,0,[],462390,NULL,False,0,Anne Frank Was a Refugee Denied Entrance to th...,45631,[]
21,Thu Oct 08 12:10:39 +0000 2015,0,[],387620,NULL,False,0,RT http://t.co/Ld9Wg1PPwn VIDEO: Tesco shopper...,143756,[]
22,Thu Sep 10 11:54:44 +0000 2015,0,[],338499,NULL,False,0,"Sanders 41%, Clinton 40% in Iowa: Bernie Sande...",219672,[]
23,Wed Jul 29 19:06:47 +0000 2015,0,"[Another, PowerMoveToVictimizeAnother, MentalH...",269733,NULL,False,0,Dr.Walter Palmer accused of sexual harassment ...,107449,[]
24,Sun Sep 13 19:29:46 +0000 2015,0,[],341917,NULL,False,0,"Watch what happens when desperate, starving Mu...",218007,[]
25,Sat Nov 21 17:52:55 +0000 2015,0,[],468358,NULL,False,0,Lmbao https://t.co/QF57Kj5lAE,53030,[]
26,Mon Jul 27 03:35:15 +0000 2015,0,[],255719,NULL,False,0,"Watch ""Judge Greg Mathis Dissects The Arrest &...",169990,[]
27,Tue Dec 08 23:51:21 +0000 2015,0,[],519071,NULL,False,0,Burt Reynolds in Hot Water After Sharing Harsh...,167308,[]
28,Sun May 31 18:35:39 +0000 2009,0,[fb],40910,NULL,False,0,"Is it me, or does the new PSP Go just look lik...",146059,[]
29,Tue Jun 09 21:30:01 +0000 2015,0,[],112387,NULL,False,0,Bold McKinney Pastor Says It's Not Just the Be...,191251,[10774652]
...,...,...,...,...,...,...,...,...,...,...
539577,Thu Jul 30 02:32:43 +0000 2015,0,[],271747,NULL,False,0,Did A Real Life 'Fallen Angel' Just Fall From ...,96721,[]
539578,Wed Jun 24 07:41:13 +0000 2015,0,[],163369,NULL,False,0,KFC uses DNA test to prove it didn't serve dee...,113663,[]
539579,Tue Jun 23 07:03:56 +0000 2015,0,[],159662,NULL,False,0,DNA test proves ‘fried rat’ was a chicken tend...,194988,[]
539580,Fri Aug 14 06:08:35 +0000 2009,0,[Cyberport],82770,NULL,False,0,#Cyberport haut gerade den Nintendo DS Lite ra...,145457,[]
539581,Tue May 26 07:23:31 +0000 2015,0,[],90186,NULL,False,0,Charlie Charlie Challenge Is A Social Media At...,116122,[]
539582,Thu Jun 17 01:45:33 +0000 2010,0,[],27286,NULL,False,0,NM gov: Harrison and Flockhart tie the knot \n...,180486,[]
539583,Thu Jun 17 09:14:07 +0000 2010,0,[],27790,NULL,False,0,► BP agrees to $20 bln oil spill fund \n (A...,45375,[]
539584,Sun Oct 11 14:17:43 +0000 2015,0,[],393865,NULL,False,0,Is McDonald's opening marijuana-friendly smoki...,153323,[]
539585,Wed Jul 08 18:59:32 +0000 2009,0,[],71850,NULL,False,0,Club Penguin sur Nintendo DS - Jeu concours & ...,170429,[]
539586,Thu Oct 08 18:56:53 +0000 2015,6,[health],388628,NULL,False,13,Survey: 1 in 3 vegetarians admits to eating me...,38132,[]
539587,Mon Jun 15 16:06:48 +0000 2015,0,[RachelDolezal],134240,NULL,False,0,BREAKING #RachelDolezal resigns as president @...,55136,[44988185]
539588,Wed Aug 19 11:30:03 +0000 2015,0,[],302118,NULL,False,0,Poll: Trump now in play for general election ...,209308,[]
539589,Thu Jul 30 17:47:09 +0000 2015,0,[],274273,NULL,False,0,This Is How People In China Are Riding Escalat...,5037,[]
539590,Wed Jul 01 18:41:51 +0000 2015,0,[],191120,NULL,False,0,Dukes of Hazzard cancelled by means of TELEVIS...,95485,[]
539591,Sat Dec 05 14:54:11 +0000 2015,0,[],512094,NULL,False,0,Zuckerberg explained why they opted for an LLC...,110783,[]
539592,Tue Jul 28 03:23:46 +0000 2015,0,[],259072,NULL,False,0,What Sandra Bland's death says about our crazy...,216828,[]
539593,Mon Jun 08 19:16:42 +0000 2015,0,[McKinney],102601,NULL,False,0,Nat Bar Association Demands TX Cop Fired Over ...,152655,[]
539594,Thu May 20 02:26:37 +0000 2010,0,[],17728,NULL,False,0,AP: North Korea warns that any retaliation ove...,80192,[]
539595,Mon Aug 03 16:20:12 +0000 2015,1,"[DefundPP, PJNET]",283816,NULL,False,5,MT @CalFreedomMom: @SenateMajLdr McConnell say...,179624,"[162114552, 1249982359]"
539596,Mon Jun 08 00:59:48 +0000 2015,0,[],99108,NULL,False,0,"McKinney, Texas policeman pulls gun on teens a...",116122,[]
539597,Sat Jul 25 23:55:35 +0000 2015,0,[],253015,NULL,False,0,Blake Shelton Returns to the Stage for First C...,155816,[]
539598,Thu Nov 05 17:54:15 +0000 2015,0,[],435533,NULL,False,0,Rupert Murdoch Took Over at National Geographi...,83789,[20818801]
539599,Thu Sep 03 01:20:55 +0000 2015,0,[],326864,NULL,False,0,Woman Ridicules Store Bagger For Being Too Slo...,168988,[]
539600,Fri Jul 17 07:07:35 +0000 2015,0,[],220724,NULL,False,0,Eating Kale Is Making People Seriously Sick ht...,188526,[]
539601,Thu Jul 01 21:50:03 +0000 2010,0,[],32540,NULL,False,0,$20 million settlement for California captive ...,178151,[]
539602,Thu Aug 20 16:51:52 +0000 2015,0,[],303785,NULL,True,0,Back to School with a $100 JCPenney Coupon htt...,167986,[]
539603,Sat Aug 01 18:32:50 +0000 2015,0,[],279467,NULL,False,0,Trump Campaign tweeted a photo with Nazi soldi...,7331,[]
539604,Mon Dec 01 16:40:02 +0000 2008,0,[],671,NULL,False,0,Sega has released the Japanese TV commercial o...,33115,[]
539605,Sat Jul 11 18:34:34 +0000 2015,0,[],213926,NULL,False,0,University student protests parking fines with...,204157,[]
539606,Fri Dec 04 06:04:48 +0000 2015,0,[],500137,NULL,False,0,"Scott Weiland, Former Singer of Stone Temple P...",100060,[9695312]

In [ ]:
user_list = df["user_id"].values
articles_id